apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: lark-webhook
  namespace: argo
spec:
  entrypoint: send
  arguments:
    parameters:
      - name: url
        value: ""
      - name: content
        value: "from request leman0"
      - name: res_url
        value: ""
      - name: message
        value: "from response leman0"
      - name: api-key
        value: ""
  templates:
  - name: send
    steps:
      - - name: call-http
          template: http
          arguments:
            parameters:
              - name: url
                value: "{{workflow.parameters.url}}"
              - name: content
                value: "{{workflow.parameters.content}}"
              - name: res_url
                value: "{{workflow.parameters.res_url}}"
              - name: message
                value: "{{workflow.parameters.message}}"
              - name: api-key
                value: "{{workflow.parameters.api-key}}"
        # 输出响应

  - name: http
    inputs:
      parameters:
        - name: url
        - name: content
        - name: res_url
        - name: message
    outputs:
      parameters:
        - name: response-body
          valueFrom:
            parameter: "{{response.body}}"
    http:
      timeoutSeconds: 20
      url: "{{inputs.parameters.url}}"
      method: "POST"
      body: |
        {
           "content": "{{inputs.parameters.content}}"
        }
      headers:
        - name: "Content-Type"
          value: "application/json"
        - name: "Authorization"
          value: "api-key {{inputs.parameters.api-key}}"
      successCondition: "response.statusCode == 200"

