services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
    - 9090:9090
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - ./file.yml:/etc/prometheus/file.yml
    - ./data:/prometheus
    - ./rules:/etc/prometheus/rules
    networks:
      local:
        ipv4_address: 192.168.100.205
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.enable-lifecycle

networks:
  local:
    external: true
