services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: 123456
    # ports:
    #   - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      local:
        ipv4_address: 192.168.100.203

networks:
  local:
    external: true
